[2024-11-10T13:11:48.047+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T13:11:41.846040+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
